files:
  - source: /static/_locales/en_US/messages.json
    translation: /static/_locales/%locale_with_underscore%/messages.json
  - source: /static/json/languages/en_US.json
    translation: /static/json/languages/%locale_with_underscore%.json
